travis:
  secure:
    BINSTAR_TOKEN: m7zR2mXcV4mlNkBR+nzFdwecH2JxrIERp4atC6iWyDcoZiNUVIQUZ4PQTBpODhegRPNyrH43NxcxDv1DkUxGKN8hdrh+2EkWcKY+PVDpebNCjvAmGBCOM8i2FQv+h1hQWADluAUOzhN8Ai+uelXAx+mN5RBdinyTqt6dzWgoHfx4uJLnWiXNQsRHHT8t+t1cMIXwQB0k9ia3p9GxTQFS8ykISQaGWM7yLT3ZkWWWe7F01GaAO+Lt4c1aw54zqzlo96Obi6UrVIi4RUbk9rQwFSH50jq/5649Ki/4WXISaXZ8p4vEpoxXh02Jildb9d75aVfRACIuWl/cAikM67v87GKL8PBSmAhxfhgodMveJ+2K6vim4FZxXhqdrwjuu8oSde6FLfrGZx4IjOq2rdDLBF5HTg7NfyE2pX/HrMur/Q/WXL4izyxqJSFeargF8kDe7yUIPeBsPyWd3Dthe4DX+thcQaCbFfJKfzr0yJJMpXJnm2Y2YWRZySUB76MSzDh4Q5sPpvuaFccWMx9Y+hx7obOTErO1tMLNzYwQEfIAQSyiVqWPFtYpe7AxQzLp9aaIns6iTQPt2a5glsf3oPa4zpcL6T8c+koFp7O/t/7xsF2nq/VsW79L1xv/zHW+QS1LaZyHdP95rysaabi9EFfqqtrkZBMibuG02/oIW24nKK0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
